import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, mkdir, writeFile, readFile, rm, readdir, chmod } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { preflight } from '../src/preflight.ts';
import { formatRemoteStatus } from '../src/remote-status.ts';
import { registryFingerprint } from '../src/handoff.ts';
import { collectSnapshot } from '../src/snapshot.ts';
import { projectQueueIssue } from '../src/github-queue.ts';
import type { Registry, RepositoryQueue } from '../src/types.ts';
async function fixture(t:test.TestContext){const root=await realpath(await mkdtemp('/private/tmp/connection-'));t.after(()=>rm(root,{recursive:true,force:true}));for(const n of ['clone','state','control'])await mkdir(join(root,n),{mode:0o700});const registry:Registry={version:1,globalConcurrency:1,repositories:[{id:'test--manager',repo:'test/manager',clonePath:join(root,'clone'),stateDirectory:join(root,'state'),enabled:true,ownership:'observe-only',defaultModel:'gpt-6.1-sol',defaultEffort:'medium',maximumConcurrency:1}]};const engine=await import(new URL('../engine/care-record/profiles.mjs',import.meta.url).href);await writeFile(join(root,'clone/package.json'),JSON.stringify({name:'local-ai-manage',scripts:engine.managerScripts}));const state={version:1,repo:'test/manager',status:'idle',paused:false,current:null,nextRetryAt:null,quotaWaitStarted:null,secret:'SECRET_CANARY',session:'SESSION_CANARY'};await writeFile(join(root,'state/state.json'),JSON.stringify(state),{mode:0o600});await writeFile(join(root,'control/handoff.json'),JSON.stringify({version:1,registryFingerprint:registryFingerprint(registry),standaloneStopped:true,scope:'all-registered-workers',repositories:[{repositoryId:'test--manager',profile:'local-ai-manage-v1'}]}),{mode:0o600});return {root,registry,state};}
test('offline preflight keeps all bytes and files, never infers process stop or dispatch authorization',async t=>{const f=await fixture(t);const bytes=await readFile(join(f.root,'state/state.json'));const control=await readdir(join(f.root,'control'));let auth=0;const report=await preflight(f.registry,join(f.root,'control'),{authenticate:async()=>{auth++;return true;},now:1000});assert.equal(auth,0);assert.equal(report.status,'review-required');assert.equal(report.authorizesDispatch,false);assert.ok(report.findings.some(v=>v.check==='profile'&&v.status==='pass'));assert.ok(report.findings.some(v=>v.check==='process-stop'&&v.status==='review-required'));assert.deepEqual(await readFile(join(f.root,'state/state.json')),bytes);assert.deepEqual(await readdir(join(f.root,'control')),control);for(const word of [f.root,'SECRET_CANARY','SESSION_CANARY'])assert.ok(!JSON.stringify(report).includes(word));});
test('preflight blocks locks, recovery, quota, invalid handoff and changed scripts without clearing evidence',async t=>{const f=await fixture(t);await writeFile(join(f.root,'state/worker.lock'),'PRIVATE_PID');await writeFile(join(f.root,'control/recovery.lock'),'PRIVATE_RECOVERY');await writeFile(join(f.root,'state/state.json'),JSON.stringify({...f.state,status:'quota-wait',nextRetryAt:2000}),{mode:0o600});await writeFile(join(f.root,'clone/package.json'),JSON.stringify({name:'local-ai-manage',scripts:{test:'echo SECRET_CANARY'}}));const result=await preflight(f.registry,join(f.root,'control'),{github:true,authenticate:async()=>false,now:1000});assert.equal(result.status,'blocked');for(const check of ['worker.lock','recovery','quota','profile','github-auth'])assert.ok(result.findings.some(v=>v.check===check&&v.status==='blocked'));assert.equal(await readFile(join(f.root,'state/worker.lock'),'utf8'),'PRIVATE_PID');assert.ok(!JSON.stringify(result).includes('SECRET_CANARY'));await writeFile(join(f.root,'control/handoff.json'),'{}');assert.ok((await preflight(f.registry,join(f.root,'control'))).findings.some(v=>v.check==='handoff'&&v.status==='blocked'));});
test('preflight treats missing directories and unsafe state as blockers and failed authentication as fixed output',async t=>{const f=await fixture(t);await chmod(join(f.root,'state/state.json'),0o644);assert.ok((await preflight(f.registry,join(f.root,'control'))).findings.some(v=>v.check==='state-permissions'&&v.status==='blocked'));const report=await preflight(f.registry,join(f.root,'missing'),{github:true,authenticate:async()=>{throw new Error('SECRET_CANARY');}});assert.equal(report.status,'blocked');assert.ok(!JSON.stringify(report).includes('SECRET_CANARY'));assert.ok(!(await readdir(f.root)).includes('missing'));});
test('remote body follows #73 markers with bounded queue and explicit absent/stale/stopped heartbeat',async t=>{const f=await fixture(t);const snapshot=(await collectSnapshot(f.registry,1000)).repositories[0]!;const queue:RepositoryQueue={repositoryId:snapshot.id,repo:snapshot.repo,status:'observed',reason:'observed',updatedAt:new Date(1000).toISOString(),items:Array.from({length:7},(_,i)=>({repositoryId:snapshot.id,repo:snapshot.repo,issue:i+1,priority:'p1',prioritySource:'metadata',dependencies:[],status:'ready',reason:'eligible'}))};const unknown=formatRemoteStatus(snapshot,queue,1000);assert.ok(unknown.includes('Worker: unknown'));assert.ok(!unknown.includes('codex-worker-heartbeat:'));assert.ok(unknown.includes('7 ready'));assert.ok(!unknown.includes('#6'));snapshot.heartbeat={at:new Date(1000).toISOString(),status:'stale'};assert.ok(formatRemoteStatus(snapshot,queue,901000).includes('Worker: heartbeat observed'));assert.ok(formatRemoteStatus(snapshot,queue,901001).includes('Worker: heartbeat stale'));assert.ok(formatRemoteStatus(snapshot,queue,901001).includes('Queue: unavailable'));snapshot.heartbeat.status='stopped';assert.ok(formatRemoteStatus(snapshot,undefined,1001).includes('Worker: stopped'));snapshot.heartbeat.at=new Date(2000).toISOString();assert.ok(formatRemoteStatus(snapshot,queue,1000).includes('Worker: unknown'));snapshot.status='SECRET_CANARY';snapshot.current={issue:2,stage:'unknown',failures:0,quotaWaits:0,reasonCategories:['SECRET_CANARY'],model:'SECRET_CANARY',effort:null,check:null,prUrl:null};for(const word of ['SECRET_CANARY','SESSION_CANARY',f.root])assert.ok(!formatRemoteStatus(snapshot,queue,1000).includes(word));});
test('marked status Issues cannot enter consumer or fixed worker queue even if ready-labelled',async t=>{const f=await fixture(t);const marked={number:1,state:'open',body:'<!-- codex-worker-status -->',labels:['codex:ready'],title:'status'};assert.equal(projectQueueIssue(marked,f.registry.repositories[0]!),null);const engine=await import(new URL('../engine/care-record/lib/queue.mjs',import.meta.url).href);assert.equal(engine.selectIssue([marked],new Map()),null);assert.equal(engine.selectIssue([marked,{...marked,number:2,body:''}],new Map()).number,2);});
test('CLI diagnostics use synthetic Git registry without controller creation or remote writes',async t=>{const f=await fixture(t);execFileSync('git',['init','-q',join(f.root,'clone')]);execFileSync('git',['-C',join(f.root,'clone'),'remote','add','origin','https://github.com/test/manager.git']);const config=join(f.root,'registry.json');await writeFile(config,JSON.stringify(f.registry));const invoke=(flags:string[])=>execFileSync(process.execPath,['--experimental-strip-types',new URL('../src/cli.ts',import.meta.url).pathname,'--registry',config,...flags],{encoding:'utf8'});const pre=JSON.parse(invoke(['--preflight','--controller-state',join(f.root,'control')]));assert.equal(pre.authorizesDispatch,false);assert.equal(pre.status,'review-required');const remote=JSON.parse(invoke(['--remote-status']));assert.ok(remote[0].body.includes('<!-- codex-worker-status -->'));assert.ok(!(await readdir(join(f.root,'control'))).includes('controller.lock'));assert.throws(()=>invoke(['--preflight','--controller-state',join(f.root,'control'),'--execute','--github']));});

test('diagnostic JSON and profile reads reject named pipes without waiting for a writer',async t=>{const f=await fixture(t);execFileSync('git',['init','-q',join(f.root,'clone')]);execFileSync('git',['-C',join(f.root,'clone'),'remote','add','origin','https://github.com/test/manager.git']);const config=join(f.root,'registry.json');await writeFile(config,JSON.stringify(f.registry));for(const path of ['clone/package.json','state/state.json']){await rm(join(f.root,path));execFileSync('mkfifo',[join(f.root,path)]);}let output='';try{execFileSync(process.execPath,['--experimental-strip-types',new URL('../src/cli.ts',import.meta.url).pathname,'--registry',config,'--preflight','--controller-state',join(f.root,'control')],{encoding:'utf8',timeout:3000});assert.fail('must block');}catch(error){const failure=error as {status:number;stdout:string};assert.equal(failure.status,2);output=failure.stdout;}assert.equal(JSON.parse(output).status,'blocked');const engine=await import(new URL('../engine/care-record/profiles.mjs',import.meta.url).href);for(const name of ['preflight','remote-status'])assert.equal(engine.managerProtected([' M src/'+name+'.ts']),true);});
