import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, realpath, mkdir, rm, readFile, writeFile, symlink } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { producerManifest, producerPlan, producerBundleDirectory, producerDirectory } from '../src/producer-plan.ts';
import type { Registry } from '../src/types.ts';
async function fixture(t:test.TestContext,basis:'development'|'dedicated'='development'){const root=await realpath(await mkdtemp('/private/tmp/producer-bundle-'));t.after(()=>rm(root,{recursive:true,force:true}));const clone=join(root,'clone'),state=join(root,'state');await mkdir(clone);await mkdir(state,{mode:0o700});const manifest=await producerManifest(basis);for(const entry of manifest.files){if(entry.before===null)continue;const path=join(clone,entry.path);await mkdir(dirname(path),{recursive:true});await writeFile(path,await readFile(join(producerDirectory(basis),'baseline',entry.path+'.txt')));}await writeFile(join(clone,'package.json'),JSON.stringify({name:'care-record-app',type:'module'}));execFileSync('git',['init','-q',clone]);execFileSync('git',['-C',clone,'remote','add','origin','https://github.com/test/care-record.git']);const registry:Registry={version:1,globalConcurrency:1,repositories:[{id:'test--care-record',repo:'test/care-record',clonePath:clone,stateDirectory:state,enabled:false,ownership:'observe-only',defaultModel:'gpt-6.1-sol',defaultEffort:'medium',maximumConcurrency:1}]};await writeFile(join(state,'state.json'),'STATE_SESSION_QUOTA_CANARY');return {root,clone,state,registry,manifest};}
test('review bundle checks captured baseline and CLI stays offline/read-only',async t=>{const f=await fixture(t);const original=await readFile(join(f.clone,'scripts/codex/continuous-worker.mjs'));const result=await producerPlan(f.registry);assert.equal(result.authorizesApply,false);assert.equal(result.repositories[0]?.status,'ready-for-review');assert.deepEqual(await readFile(join(f.clone,'scripts/codex/continuous-worker.mjs')),original);assert.equal(await readFile(join(f.state,'state.json'),'utf8'),'STATE_SESSION_QUOTA_CANARY');const config=join(f.root,'registry.json');await writeFile(config,JSON.stringify(f.registry));const args=['--experimental-strip-types',new URL('../src/cli.ts',import.meta.url).pathname,'--registry',config,'--producer-plan'];assert.equal(JSON.parse(execFileSync(process.execPath,args,{encoding:'utf8'})).repositories[0].status,'ready-for-review');assert.throws(()=>execFileSync(process.execPath,[...args,'--github'],{stdio:'pipe'}));});
test('bundle applies only in a synthetic copy and patched legacy worker passes its full regression suite',async t=>{const f=await fixture(t);const patch=join(producerBundleDirectory,'producer.patch');execFileSync('git',['-C',f.clone,'apply','--check',patch]);execFileSync('git',['-C',f.clone,'apply',patch]);for(const entry of f.manifest.files)assert.equal(createHash('sha256').update(await readFile(join(f.clone,entry.path))).digest('hex'),entry.after);assert.equal((await producerPlan(f.registry)).repositories[0]?.status,'already-present');const tests=f.manifest.files.filter(v=>v.path.endsWith('.test.mjs')).map(v=>v.path);const childEnv={...process.env};delete childEnv.NODE_TEST_CONTEXT;const {stdout}=await promisify(execFile)(process.execPath,['--test',...tests],{cwd:f.clone,timeout:30000,maxBuffer:1048576,env:childEnv});assert.match(stdout,/(?:fail 0|# fail 0)/);assert.match(stdout,/(?:tests 101|# tests 101)/);assert.equal(await readFile(join(f.state,'state.json'),'utf8'),'STATE_SESSION_QUOTA_CANARY');});
test('source drift, partial installation, unsupported package and symlinks require review without raw data disclosure',async t=>{const f=await fixture(t);const path=join(f.clone,'scripts/codex/lib/queue.mjs');const original=await readFile(path);await writeFile(path,original+'\n// PHI_CANARY\n');const result=await producerPlan(f.registry);assert.equal(result.repositories[0]?.status,'blocked');assert.ok(!JSON.stringify(result).includes('PHI_CANARY'));await writeFile(path,original);execFileSync('git',['-C',f.clone,'apply',join(producerBundleDirectory,'producer.patch')]);await writeFile(path,original);assert.equal((await producerPlan(f.registry)).repositories[0]?.status,'blocked');await rm(path);await symlink(join(f.clone,'scripts/codex/continuous-worker.mjs'),path);assert.equal((await producerPlan(f.registry)).repositories[0]?.status,'blocked');await writeFile(join(f.clone,'package.json'),JSON.stringify({name:'other'}));assert.equal((await producerPlan(f.registry)).repositories[0]?.status,'unsupported');});

test('dedicated source selects its own bundle and retains deployment and broader verification safeguards',async t=>{const f=await fixture(t,'dedicated');const before=await readFile(join(f.clone,'scripts/codex/lib/publication.mjs'));const verification=await readFile(join(f.clone,'scripts/codex/lib/verification.mjs'));const plan=await producerPlan(f.registry);assert.equal(plan.repositories[0]?.status,'ready-for-review');assert.equal('basis' in plan.repositories[0]!&&plan.repositories[0].basis,'dedicated');execFileSync('git',['-C',f.clone,'apply','--check',join(producerDirectory('dedicated'),'producer.patch')]);execFileSync('git',['-C',f.clone,'apply',join(producerDirectory('dedicated'),'producer.patch')]);assert.deepEqual(await readFile(join(f.clone,'scripts/codex/lib/publication.mjs')),before);assert.deepEqual(await readFile(join(f.clone,'scripts/codex/lib/verification.mjs')),verification);assert.equal((await producerPlan(f.registry)).repositories[0]?.status,'already-present');const env={...process.env};delete env.NODE_TEST_CONTEXT;const {stdout}=await promisify(execFile)(process.execPath,['--test',...f.manifest.files.filter(v=>v.path.endsWith('.test.mjs')).map(v=>v.path)],{cwd:f.clone,env,timeout:30000,maxBuffer:1048576});assert.match(stdout,/tests 103/);assert.match(stdout,/fail 0/);});
