import { execFileSync } from 'node:child_process';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm, writeFile, readFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { parseStatusTargets, loadStatusTargets, statusArgs, remoteHeartbeat, StatusPublisher, monitorStatus, lockPublisher } from '../src/status-publisher.ts';
import type { StatusRequest } from '../src/status-publisher.ts';
import { demoSnapshot } from '../src/snapshot.ts';
const target={repositoryId:'example--care-record',repo:'example/care-record',issue:99,comment:123};
const config={version:1 as const,registryFingerprint:'a'.repeat(64),targets:[target]};
const issue={number:99,state:'open',body:'<!-- codex-worker-status -->',labels:[]};
const comment=(body:string)=>({id:123,issue_url:'https://api.github.com/repos/example/care-record/issues/99',body});
const initial='<!-- codex-worker-status -->\n';
const snapshot=(now=1000)=>{const value=demoSnapshot(now);value.repositories[0]!.heartbeat={at:new Date(now).toISOString(),status:'updating'};return value;};
test('strict targets and fixed transport cannot inject endpoints, commands, or create duplicate comments',()=>{assert.deepEqual(parseStatusTargets(config),config);for(const bad of [{...config,secret:'SECRET'},{...config,targets:[target,target]},{...config,targets:[{...target,repo:'../bad'}]},{...config,targets:[{...target,comment:-1}]},{...config,targets:[{...target,command:'shell'}]}])assert.throws(()=>parseStatusTargets(bad));assert.deepEqual(statusArgs(target,'comment',true),['api','--hostname','github.com','--method','PATCH','repos/example/care-record/issues/comments/123','--input','-']);assert.throws(()=>statusArgs(target,'issue',true));});
test('publisher reuses the fixed comment and sends transitions immediately but heartbeats at five minutes',async()=>{let body=initial;let writes=0;const request:StatusRequest=async(_t,r,next)=>{if(r==='issue')return issue;if(next){body=next;writes++;}return comment(body);};const publisher=new StatusPublisher(config,request);assert.equal((await publisher.tick(snapshot(),1000))[0]?.status,'published');await publisher.tick(snapshot(16000),16000);assert.equal(writes,1);await publisher.tick(snapshot(301000),301000);assert.equal(writes,2);const changed=snapshot(302000);changed.repositories[0]!.paused=false;await publisher.tick(changed,302000);assert.equal(writes,3);for(const word of ['session','worktree','TOKEN_CANARY'])assert.ok(!body.includes(word));});
test('publication failures neither mutate worker snapshot nor consume retries and are bounded',async()=>{const value=snapshot();const original=JSON.stringify(value);let calls=0;const publisher=new StatusPublisher(config,async()=>{calls++;throw new Error('SECRET_CANARY');});assert.equal((await publisher.tick(value,1000))[0]?.status,'unavailable');assert.equal(JSON.stringify(value),original);await publisher.tick(value,2000);assert.equal(calls,1);await publisher.tick(value,301000);assert.equal(calls,2);});
test('wrong issue/comment binding, queue labels, missing markers and changed remote text prevent PATCH',async()=>{for(const which of ['issue','comment','race','newer']){let reads=0;let writes=0;const request:StatusRequest=async(_t,r,body)=>{if(body){writes++;return comment(body);}if(r==='issue')return which==='issue'?{...issue,labels:['codex:ready']}:issue;reads++;return which==='comment'?{...comment(initial),issue_url:'https://api.github.com/repos/example/care-record/issues/2'}:comment(which==='race'&&reads>1?initial+'ADMIN_CANARY':which==='newer'?'<!-- codex-worker-status -->\n<!-- codex-worker-heartbeat: 1970-01-01T00:00:02.000Z -->\n':initial);};const result=await new StatusPublisher(config,request).tick(snapshot(),3000);assert.equal(result[0]?.status,'unavailable');assert.equal(writes,0);}});
test('restart uses remote update time to suppress early heartbeat writes',async()=>{let writes=0;let body=initial;const request:StatusRequest=async(_t,r,next)=>{if(r==='issue')return issue;if(next){writes++;body=next;}return {...comment(body),updated_at:new Date(1000).toISOString()};};await new StatusPublisher(config,request).tick(snapshot(),1000);await new StatusPublisher(config,request).tick(snapshot(16000),16000);assert.equal(writes,1);});
test('independent stale monitor is read-only and reports only allowlisted timestamps and states',async()=>{const body='<!-- codex-worker-status -->\n<!-- codex-worker-heartbeat: 1970-01-01T00:00:01.000Z -->\nPRIVATE_SESSION PHI_CANARY';let writes=0;const request:StatusRequest=async(_t,r,next)=>{if(next)writes++;return r==='issue'?issue:comment(body);};assert.equal((await monitorStatus(config,request,901000)).repositories[0]?.status,'observed');const result=await monitorStatus(config,request,901001);assert.equal(result.repositories[0]?.status,'stale');assert.equal(writes,0);assert.ok(!JSON.stringify(result).includes('PHI_CANARY'));assert.equal(remoteHeartbeat(body,500).status,'unknown');assert.equal(remoteHeartbeat(body+body,901001).status,'unknown');assert.equal(remoteHeartbeat(body+'\n- Worker: stopped\n',901001).status,'stopped');});
test('publisher private targets and exclusive lock survive restart and never clear ambiguous locks',async t=>{const directory=await realpath(await mkdtemp('/private/tmp/publisher-'));t.after(()=>rm(directory,{recursive:true,force:true}));await writeFile(join(directory,'targets.json'),JSON.stringify(config),{mode:0o600});assert.deepEqual(await loadStatusTargets(directory),config);const release=await lockPublisher(directory);await assert.rejects(lockPublisher(directory));assert.equal(await readFile(join(directory,'publisher.lock'),'utf8'),'{"version":1}');await release();const again=await lockPublisher(directory);await again();});

test('standalone Actions monitor shares heartbeat semantics and contains no mutation path',async()=>{const helper=await import(new URL('../engine/status-monitor.mjs',import.meta.url).href);const t={repo:target.repo,issue:target.issue,comment:target.comment};assert.deepEqual(helper.monitorTarget({GITHUB_REPOSITORY:t.repo,STATUS_ISSUE:'99',STATUS_COMMENT:'123'}),t);assert.throws(()=>helper.monitorTarget({GITHUB_REPOSITORY:'../attack',STATUS_ISSUE:'99',STATUS_COMMENT:'123'}));const body='<!-- codex-worker-status -->\n<!-- codex-worker-heartbeat: 1970-01-01T00:00:01.000Z -->\nPHI_CANARY';const paths:string[]=[];const result=await helper.runMonitor(t,async(path:string)=>{paths.push(path);return path.endsWith('/99')?issue:comment(body);},901001);assert.equal(result.status,'stale');assert.equal(paths.length,2);assert.ok(!JSON.stringify(result).includes('PHI_CANARY'));assert.deepEqual(helper.classifyHeartbeat(body,901001),remoteHeartbeat(body,901001));});
test('publisher enforces registry-bound private targets and monitor failures expose no raw errors',async t=>{const directory=await realpath(await mkdtemp('/private/tmp/publisher-validation-'));t.after(()=>rm(directory,{recursive:true,force:true}));await writeFile(join(directory,'targets.json'),JSON.stringify(config),{mode:0o600});await assert.rejects(loadStatusTargets(directory,{version:1,globalConcurrency:1,repositories:[]}));assert.equal((await monitorStatus(config,async()=>{throw new Error('TOKEN_CANARY');})).repositories[0]?.status,'unavailable');const result=await monitorStatus(config,async(_t,r)=>r==='issue'?issue:{...comment(initial),id:124});assert.equal(result.repositories[0]?.status,'unavailable');assert.ok(!JSON.stringify(result).includes('TOKEN_CANARY'));});
test('shutdown request prevents contacting additional targets',async()=>{const result=await new StatusPublisher(config,async()=>{assert.fail('must not call');}).tick(snapshot(),1000,()=>true);assert.deepEqual(result,[]);});

test('monitor CLI and standalone script use fake gh GET only and reject publisher flags before any transport',async t=>{const directory=await realpath(await mkdtemp('/private/tmp/publisher-cli-'));t.after(()=>rm(directory,{recursive:true,force:true}));await writeFile(join(directory,'targets.json'),JSON.stringify(config),{mode:0o600});await mkdir(join(directory,'bin'));const fake=`#!/bin/sh
case "$*" in
*'--method GET repos/example/care-record/issues/99') printf '%s' '${JSON.stringify(issue)}';;
*'--method GET repos/example/care-record/issues/comments/123') printf '%s' '${JSON.stringify(comment(initial))}';;
*) exit 99;;
esac
`;await writeFile(join(directory,'bin/gh'),fake,{mode:0o700});const env={PATH:join(directory,'bin')+':'+process.env.PATH,HOME:directory};let output='';try{execFileSync(process.execPath,['--experimental-strip-types',new URL('../src/cli.ts',import.meta.url).pathname,'--status-monitor',directory],{env,encoding:'utf8'});assert.fail('unknown heartbeat must be nonzero');}catch(error){const failure=error as {status:number;stdout:string};assert.equal(failure.status,2);output=failure.stdout;}assert.equal(JSON.parse(output).repositories[0].status,'unknown');assert.throws(()=>execFileSync(process.execPath,['--experimental-strip-types',new URL('../src/cli.ts',import.meta.url).pathname,'--status-publisher',directory,'--demo'],{env,encoding:'utf8',stdio:'pipe'}));try{execFileSync(process.execPath,[new URL('../engine/status-monitor.mjs',import.meta.url).pathname],{env:{...env,GITHUB_REPOSITORY:target.repo,STATUS_ISSUE:'99',STATUS_COMMENT:'123'},encoding:'utf8'});assert.fail('unknown must be nonzero');}catch(error){const failure=error as {status:number;stdout:string};assert.equal(failure.status,2);assert.equal(JSON.parse(failure.stdout).status,'unknown');}});
