import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { ReadinessService, demoReadiness } from '../src/readiness.ts';
import { Controller } from '../src/controller.ts';
import { collectSnapshot } from '../src/snapshot.ts';
import { startServer } from '../src/server.ts';
import type { Registry } from '../src/types.ts';
async function fixture(t:test.TestContext){const root=await realpath(await mkdtemp('/private/tmp/readiness-'));const cleanup:(()=>Promise<void>)[]=[];t.after(async()=>{for(const close of cleanup)await close();await rm(root,{recursive:true,force:true});});for(const n of ['clone','state','web'])await mkdir(join(root,n),{mode:0o700});const registry:Registry={version:1,globalConcurrency:1,repositories:[{id:'test--manager',repo:'test/manager',clonePath:join(root,'clone'),stateDirectory:join(root,'state'),enabled:false,ownership:'observe-only',defaultModel:'gpt-6.1-sol',defaultEffort:'medium',maximumConcurrency:1}]};const engine=await import(new URL('../engine/care-record/profiles.mjs',import.meta.url).href);await writeFile(join(root,'clone/package.json'),JSON.stringify({name:'local-ai-manage',scripts:engine.managerScripts}));const state=JSON.stringify({version:1,repo:'test/manager',status:'idle',paused:true,current:null,nextRetryAt:null,quotaWaitStarted:null,secret:'PHI_CANARY',session:'SESSION_CANARY'});await writeFile(join(root,'state/state.json'),state,{mode:0o600});await writeFile(join(root,'web/index.html'),'shell');return {root,registry,state,cleanup};}
test('readiness caches immutable diagnostics and preserves every worker/controller byte',async t=>{const f=await fixture(t);const controller=await Controller.create(f.registry,join(f.root,'controller'));f.cleanup.push(()=>controller.close());let now=1000;const service=new ReadinessService(f.registry,controller.directoryPath(),{activeDashboard:true,now:()=>now});const before=await readFile(join(f.root,'controller/controller.json'));const value=await service.get();assert.equal(value.authorizesDispatch,false);assert.ok(value.findings.some(v=>v.check==='controller.lock'&&v.status==='pass'));for(const word of [f.root,'PHI_CANARY','SESSION_CANARY'])assert.ok(!JSON.stringify(value).includes(word));value.findings.length=0;assert.ok((await service.get()).findings.length>0);now=31000;assert.equal((await service.get()).checkedAt,new Date(now).toISOString());assert.equal(await readFile(join(f.root,'state/state.json'),'utf8'),f.state);assert.deepEqual(await readFile(join(f.root,'controller/controller.json')),before);});
test('readiness API keeps authentication/origin/query boundaries and accepts no commands or paths',async t=>{const f=await fixture(t);const service=new ReadinessService(f.registry,join(f.root,'absent'));const app=await startServer({snapshot:()=>collectSnapshot(f.registry),webDirectory:join(f.root,'web'),readiness:()=>service.get()});t.after(()=>app.close());assert.equal((await fetch(app.origin+'/api/readiness')).status,401);const login=await fetch(app.origin+'/api/session',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json','X-Local-Bootstrap':'1'},body:JSON.stringify({nonce:new URL(app.launchUrl).hash.slice(1)})});const cookie=login.headers.get('set-cookie')!.split(';')[0]!;const headers={Cookie:cookie};const response=await fetch(app.origin+'/api/readiness',{headers});assert.equal(response.status,200);const bytes=await response.text();assert.equal(JSON.parse(bytes).authorizesDispatch,false);for(const word of [f.root,'PHI_CANARY','SESSION_CANARY'])assert.ok(!bytes.includes(word));assert.equal((await fetch(app.origin+'/api/readiness?path=/private',{headers})).status,400);assert.equal((await fetch(app.origin+'/api/readiness',{headers:{...headers,Origin:'https://evil.example'}})).status,403);assert.equal((await fetch(app.origin+'/api/readiness',{method:'POST',headers,body:'{"command":"resume"}'})).status,405);assert.equal(await readFile(join(f.root,'state/state.json'),'utf8'),f.state);});
test('demo diagnostics are synthetic and never authorize execution',()=>{const value=demoReadiness(1000);assert.equal(value.authorizesDispatch,false);assert.equal(value.status,'review-required');assert.equal(value.producers[0]?.basis,'dedicated');});
