// Dependency-free, read-only monitor for installation in the status repository.
import { execFile } from 'node:child_process';
import { pathToFileURL } from 'node:url';
export function classifyHeartbeat(body,now){const matches=[...body.matchAll(/<!-- codex-worker-heartbeat: ([^\n]+) -->/g)];if(matches.length!==1)return {status:'unknown',at:null};const at=matches[0][1];const n=Date.parse(at);if(!Number.isFinite(n)||n<0||n>now||new Date(n).toISOString()!==at)return {status:'unknown',at:null};return {status:body.includes('\n- Worker: stopped\n')?'stopped':now-n>900000?'stale':'observed',at};}
export function monitorTarget(env){const repo=env.GITHUB_REPOSITORY;const issue=Number(env.STATUS_ISSUE),comment=Number(env.STATUS_COMMENT);if(typeof repo!=='string'||!/^[A-Za-z0-9][A-Za-z0-9_.-]*\/[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(repo)||repo.split('/').some(v=>v==='.'||v==='..')||![issue,comment].every(v=>Number.isSafeInteger(v)&&v>0))throw new Error('invalid_monitor_target');return {repo,issue,comment};}
export async function runMonitor(target,read,now=Date.now()){
 const issue=await read(`repos/${target.repo}/issues/${target.issue}`);if(!issue||issue.number!==target.issue||issue.state!=='open'||issue.pull_request||typeof issue.body!=='string'||!issue.body.includes('<!-- codex-worker-status -->')||!Array.isArray(issue.labels)||issue.labels.some(v=>{const name=typeof v==='string'?v:v?.name;return typeof name!=='string'||name.startsWith('codex:');}))throw new Error('invalid_monitor_issue');
 const comment=await read(`repos/${target.repo}/issues/comments/${target.comment}`);if(!comment||comment.id!==target.comment||comment.issue_url!==`https://api.github.com/repos/${target.repo}/issues/${target.issue}`||typeof comment.body!=='string'||comment.body.length>65536||!comment.body.startsWith('<!-- codex-worker-status -->\n')||comment.body.split('<!-- codex-worker-status -->').length!==2)throw new Error('invalid_monitor_comment');
 return {version:1,checkedAt:new Date(now).toISOString(),...classifyHeartbeat(comment.body,now)};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){
 try{const target=monitorTarget(process.env);const read=resource=>new Promise((resolve,reject)=>execFile('gh',['api','--hostname','github.com','--method','GET',resource],{timeout:10000,killSignal:'SIGKILL',maxBuffer:1048576,shell:false,env:Object.fromEntries(['PATH','HOME','GH_TOKEN','GITHUB_TOKEN','GH_CONFIG_DIR'].filter(k=>process.env[k]).map(k=>[k,process.env[k]]))},(error,stdout)=>{if(error){reject(new Error('monitor_unavailable'));return;}try{resolve(JSON.parse(stdout));}catch{reject(new Error('monitor_unavailable'));}}));const result=await runMonitor(target,read);console.log(JSON.stringify(result));process.exitCode=['stale','unknown'].includes(result.status)?2:0;}catch{console.log(JSON.stringify({version:1,status:'unavailable',at:null}));process.exitCode=2;}
}
