import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import { open, realpath } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { record } from './registry.ts';
import { registryFingerprint } from './handoff.ts';
import type { Registry, Repository } from './types.ts';
const bundles={development:{id:'care-record-producer-v1',path:'care-record-producer',count:14},dedicated:{id:'care-record-dedicated-producer-v1',path:'care-record-dedicated-producer',count:16}} as const;
export type ProducerBasis=keyof typeof bundles;
export function producerDirectory(basis:ProducerBasis='development'){const descriptor=bundles[basis];if(!descriptor)throw new Error('unsupported_producer_basis');return fileURLToPath(new URL(`${import.meta.url.endsWith('.ts')?'../':'../../'}integrations/${descriptor.path}/`,import.meta.url));}
export const producerBundleDirectory=producerDirectory();
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
async function bytes(path:string){const file=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK);try{const stat=await file.stat();if(!stat.isFile()||stat.size>1048576)throw new Error('unsafe_source');const buffer=Buffer.alloc(1048577);const {bytesRead}=await file.read(buffer,0,buffer.length,0);if(bytesRead>1048576)throw new Error('oversized_source');return buffer.subarray(0,bytesRead);}finally{await file.close();}}
interface Entry {path:string;before:string|null;after:string}
export async function producerManifest(basis:ProducerBasis='development'){const directory=producerDirectory(basis),descriptor=bundles[basis];const value:unknown=JSON.parse((await bytes(join(directory,'manifest.json'))).toString());if(!record(value)||Object.keys(value).length!==5||value.version!==1||value.id!==descriptor.id||value.capturedAt!=='2026-10-04'||typeof value.patchSha256!=='string'||!/^[a-f0-9]{64}$/.test(value.patchSha256)||!Array.isArray(value.files)||value.files.length!==descriptor.count)throw new Error('invalid_producer_bundle');const seen=new Set<string>();for(const item of value.files){if(!record(item)||Object.keys(item).length!==3||typeof item.path!=='string'||!/^scripts\/codex\/(?:lib\/)?[a-z][a-z.-]*\.mjs$/.test(item.path)||seen.has(item.path)||item.before!==null&&(typeof item.before!=='string'||!/^[a-f0-9]{64}$/.test(item.before))||typeof item.after!=='string'||!/^[a-f0-9]{64}$/.test(item.after))throw new Error('invalid_producer_bundle');seen.add(item.path);if(item.before!==null&&hash(await bytes(join(directory,'baseline',item.path+'.txt')))!==item.before)throw new Error('producer_baseline_changed');}if(hash(await bytes(join(directory,'producer.patch')))!==value.patchSha256)throw new Error('producer_patch_changed');return {id:value.id,basis,patchSha256:value.patchSha256,files:value.files as unknown as Entry[]};}
async function compare(repo:Repository,manifest:Awaited<ReturnType<typeof producerManifest>>){const files=[];for(const entry of manifest.files){let actual:string|null=null;let unsafe=false;const path=join(repo.clonePath,entry.path);try{if(await realpath(path)!==path)throw new Error('changed_source');actual=hash(await bytes(path));}catch(error){if(!(error instanceof Error)||!('code' in error)||error.code!=='ENOENT')unsafe=true;}files.push({path:entry.path,status:unsafe?'blocked':actual===entry.after?'already-present':actual===entry.before?'matches-baseline':'blocked'});}const status=files.every(f=>f.status==='already-present')?'already-present':files.every((f,i)=>f.status==='matches-baseline'||f.status==='already-present'&&manifest.files[i]!.before===manifest.files[i]!.after)?'ready-for-review':'blocked';return {bundleId:manifest.id,basis:manifest.basis,patchSha256:manifest.patchSha256,status,files};}
/** Review plan only. Source evidence selects one fixed reviewed bundle; nothing is applied. */
export async function producerPlan(registry:Registry){const manifests=await Promise.all((Object.keys(bundles) as ProducerBasis[]).map(basis=>producerManifest(basis)));const repositories=[];for(const repo of registry.repositories){let supported=false;try{const pkg:unknown=JSON.parse((await bytes(join(repo.clonePath,'package.json'))).toString());supported=record(pkg)&&pkg.name==='care-record-app';}catch{/* unavailable */}if(!supported){repositories.push({repositoryId:repo.id,status:'unsupported',files:[]});continue;}const candidates=await Promise.all(manifests.map(manifest=>compare(repo,manifest)));const matching=candidates.filter(c=>c.status!=='blocked');const selected=matching.length===1?matching[0]!:candidates.sort((a,b)=>a.files.filter(f=>f.status==='blocked').length-b.files.filter(f=>f.status==='blocked').length)[0]!;repositories.push({repositoryId:repo.id,...selected,status:matching.length>1?'blocked':selected.status});}return {version:1,bundleId:'care-record-producer-catalog-v1',registryFingerprint:registryFingerprint(registry),authorizesApply:false,repositories};}
