import { preflight, type Finding } from './preflight.ts';
import { producerPlan } from './producer-plan.ts';
import type { Registry } from './types.ts';
export interface ReadinessReport {version:1;checkedAt:string;status:'blocked'|'review-required'|'unavailable';authorizesDispatch:false;findings:Finding[];producers:{repositoryId:string;basis:'development'|'dedicated'|null;status:'ready-for-review'|'already-present'|'blocked'|'unsupported'|'unavailable'}[]}
/** Cache fixed read-only diagnostics. HTTP callers supply no paths, commands, or credentials. */
export class ReadinessService {
 private registry:Registry;private directory:string;private activeDashboard:boolean;private now:()=>number;private cached:ReadinessReport|null=null;private inFlight:Promise<ReadinessReport>|null=null;private checked=0;
 constructor(registry:Registry,directory:string,{activeDashboard=false,now=Date.now}:{activeDashboard?:boolean;now?:()=>number}={}){this.registry=registry;this.directory=directory;this.activeDashboard=activeDashboard;this.now=now;}
 get():Promise<ReadinessReport>{const now=this.now();if(this.cached&&now>=this.checked&&now-this.checked<30000)return Promise.resolve(structuredClone(this.cached));this.inFlight??=this.collect(now).then(report=>{this.checked=now;this.cached=report;return report;}).finally(()=>{this.inFlight=null;});return this.inFlight.then(value=>structuredClone(value));}
 private async collect(now:number):Promise<ReadinessReport>{try{const [checks,producer]=await Promise.all([preflight(this.registry,this.directory,{now,activeDashboard:this.activeDashboard}),producerPlan(this.registry).catch(()=>null)]);const producers=producer?.repositories.map(item=>({repositoryId:item.repositoryId,basis:'basis' in item?item.basis:null,status:item.status as ReadinessReport['producers'][number]['status']}))??this.registry.repositories.map(repo=>({repositoryId:repo.id,basis:null,status:'unavailable' as const}));return {version:1,checkedAt:new Date(now).toISOString(),status:checks.status as ReadinessReport['status'],authorizesDispatch:false,findings:checks.findings,producers};}catch{return {version:1,checkedAt:new Date(now).toISOString(),status:'unavailable',authorizesDispatch:false,findings:[],producers:[]};}}
}
export function demoReadiness(now=Date.now()):ReadinessReport{return {version:1,checkedAt:new Date(now).toISOString(),status:'review-required',authorizesDispatch:false,findings:[{repositoryId:null,check:'registry',status:'pass',reason:'canonical_registry_loaded'},{repositoryId:'example--care-record',check:'worker-intervention',status:'review-required',reason:'worker_pause_or_intervention_preserved'},{repositoryId:null,check:'process-stop',status:'review-required',reason:'all_workers_children_and_restarts_require_human_confirmation'}],producers:[{repositoryId:'example--care-record',basis:'dedicated',status:'ready-for-review'}]};}
